name: Build and Deploy to S3

on:
  push:
    branches: [ main ]

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    env:
      NAME: web-integrations-docs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: ${{ env.NAME }}

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd ${{ env.NAME }}
          yarn install

      - name: Build and Export
        run: |
          cd ${{ env.NAME }}
          yarn build
          yarn export

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ env.NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
          SOURCE_DIR: ${{ env.NAME }}/out